### ISSUE TITLE
Failed to load builtins

### ISSUE THREAD

**Issue by moshanATucsd** [akanazawa/cmr#1]
Hi, thanks for sharing the code! I encountered the following error, and I am wondering how to solve this?

```
venv_cmr/local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: nvrtc: error: failed to load builtins
```

**Comment by shubhtuls** [comment]
Hi,
Could you please provide more details about where this error occurs? Is it when you're trying to install something, or if running a particular script (if yes, which line)?

**Comment by moshanATucsd** [comment]
It happens when I am running this line. I think that it's because CuPy cannot detect CUDA as explained [here](https://github.com/cupy/cupy/blob/7ba218bfc1360672e94ef7a13d0e3993fc425989/docs/source/install.rst). It seems this is an issue with cupy. Thanks for your quick reply anyway! 

```
python -m cmr.demo --name bird_net --num_train_epoch 500 --img_path cmr/demo_data/img1.jpg
```

**Comment by moshanATucsd** [comment]
BTW, I tried the solution mentioned in the link above but the error still persists. I guess it's still related to cupy and cuda path. 

Here is what I used

```
export CUDA_PATH=/usr/local/cuda-9.0
export LD_LIBRARY_PATH=$CUDA_PATH/lib64:$LD_LIBRARY_PATH
```

**Comment by y-nissi** [comment]
@moshanATucsd  I meet the same problem. how did you solve the problem?

cupy-cuda90==4.0.0b4
cuda == 9.0

this is my environment.
