### ISSUE TITLE
Do anyone can explain the orth projection?

### ISSUE THREAD

**Issue by gsygsy96** [akanazawa/cmr#12]
I'm confused about the operation that preserving z when orthogonal projecting. Code is write at this [place](https://github.com/akanazawa/cmr/blob/5d97c4e744bcdd6c3bc20866305ec382fce7fcc5/nnutils/geom_utils.py#L58)

**Comment by sunshineatnoon** [comment]
Hi, did you figure this out?

**Comment by sunshineatnoon** [comment]
I guess the purpose is to first rotate generated mesh to some view w.r.t camera parameters and then do orthogonal projection to get the image/mask.
