### ISSUE TITLE
textured human reconstruction

### ISSUE THREAD

**Issue by QHan1st** [akanazawa/cmr#14]
Professor Angjoo Kanazawa:
    I want to try to reconstruct the textured human body shape from a single image with your represent model.So,I want to ask you about whether it's feasible or not?Would you give me some suggestions about these?Thanks!
@akanazawa @shubhtuls

**Comment by akanazawa** [comment]
Hi,

Human texture is more challenging without any apriori body model since human body shape articulates and disambiguate that with shape is still very hard (in this work we ignored the articulation aspect of the birds). However with an existing human body model, many works explore extracting texture of humans. Gerard has a lot of work in this direction: https://virtualhumans.mpi-inf.mpg.de/publications.html
Also relevant is https://github.com/gulvarol/surreal to see how the humans are textured.
We also have a new work that is slightly of different representation but can recover the surface color of the unseen side from a single image: https://shunsukesaito.github.io/PIFu/

Good luck!

a

**Comment by Weipeilang** [comment]
Hi,I have a question to consult you. I just want to apply the texture to the car which is already generated.Do I need to generate the sfm of car and train as the follow again ,or can I apply the texture to car directly?Thank you!
@akanazawa

**Comment by akanazawa** [comment]
Hi, 

I'm a bit confused, is it that you have a 3D model & its camera to align it to the image, but no texture and you want to texture the model? 
In this setting it's possible to sample the visible area of the texture, should be a simple operation in graphics, see something like https://learnopengl.com/Getting-started/Textures
If you want the model to give you 3D model and the entire texture, yes you need to train with it.
If you already have a texture image, it's easy to render it with an existing 3D model. 

Hope this helps,

Best,

Angjoo

**Comment by Weipeilang** [comment]
First of all,thank you for your reply.


I want the model to give me 3D model and the entire texture.I want to apply it to the cars and I see you had accomplished it. I'm a little confused about the process,such as how to get SFM of car,could you tell me more details about this.And how to use this .mat file?



Thanks again.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"akanazawa"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 凌晨5:23
收件人:&nbsp;"akanazawa/cmr"<cmr@noreply.github.com&gt;;
抄送:&nbsp;"If you,if I"<2546954766@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [akanazawa/cmr] textured human reconstruction (#14)




Hi,
 
I'm a bit confused, is it that you have a 3D model &amp; its camera to align it to the image, but no texture and you want to texture the model?
 In this setting it's possible to sample the visible area of the texture, should be a simple operation in graphics, see something like https://learnopengl.com/Getting-started/Textures
 If you want the model to give you 3D model and the entire texture, yes you need to train with it.
 If you already have a texture image, it's easy to render it with an existing 3D model.
 
Hope this helps,
 
Best,
 
Angjoo

**Comment by akanazawa** [comment]
Hi, 

I see yes, you'd have to run it. See https://github.com/akanazawa/cmr/issues/5 for more detail. 
Depending on what you want to do, there are more methods since this publication, you might want to look at the code release of this paper: https://nv-tlabs.github.io/DIB-R/

good luck!

Angjoo
