### ISSUE TITLE
where is the results saved?

### ISSUE THREAD

**Issue by QHan1st** [akanazawa/cmr#15]
Hello:
   I run the project and it resulted in a new terminal named "ipdb",I input "c" to continue the procedure,but it return nothing but the orignal terminal.and I have not see any output results,what should I do next?Whether I run the script successfully?Thanks.

> /root/Documents/cmr/demo.py(98)visualize()
     97     import ipdb
---> 98     ipdb.set_trace()
     99 

ipdb>  
@shubhtuls @akanazawa

**Comment by akanazawa** [comment]
Hi, you should see a visualization of the results from matplotlib. You're probably not seeing it. You could save the images to file if you would like. 

Best,

a
