### ISSUE TITLE
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by QHan1st** [akanazawa/cmr#16]
When I run "python -m cmr.demo --name bird_net --num_train_epoch 500 --img_path cmr/demo_data/img1.jpg" , it shows that "cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_EXECUTION_FAILED".Is this my environment error of cupy and chainer?
My environment is that:cuda10,cudnn7.4,chainer6.2,cupy6.2.
@akanazawa @shubhtuls

**Comment by akanazawa** [comment]
This sounds like a cupy/CUDA environment issue.
