### ISSUE TITLE
360° view

### ISSUE THREAD

**Issue by felixboevr** [akanazawa/cmr#17]
Could you provide any code to get a 360° view of the model like you demoed in your video at https://youtu.be/cYHQKtBLI3Q?t=21

**Comment by akanazawa** [comment]
Hi, 

Note that in the renderer it has the option to take in view-angles https://github.com/akanazawa/cmr/blob/5d97c4e744bcdd6c3bc20866305ec382fce7fcc5/demo.py#L62
to make that kind of video, you simply render the model in every 5 or 15 angle increments and ffmpeg the resulting images together. 

Best,

Angjoo

**Comment by felixboevr** [comment]
Thank you, Angjoo. What I'm actually trying to do is to get the numpy array of the preprocessed image and visualize it via _ipyvolume_ so that you can twist and turn it. Have a look if you're interested. It's quite amazing https://ipyvolume.readthedocs.io/en/latest/index.html#volume

**Comment by akanazawa** [comment]
Super neat!! Thanks for sharing.
