### ISSUE TITLE
Undefined name 'convert2np' in ./benchmark/evaluate.py

### ISSUE THREAD

**Issue by cclauss** [akanazawa/cmr#2]
There is a missing import in ./benchmark/evaluate.py so that __convert2np()__ is and undefined name.

__convert2np()__ is defined at https://github.com/akanazawa/cmr/blob/master/utils/bird_vis.py#L177

flake8 testing of https://github.com/akanazawa/cmr on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./benchmark/evaluate.py:102:28: F821 undefined name 'convert2np'
        img = np.transpose(convert2np(batch['img'][0]), (1, 2, 0))
                           ^
1     F821 undefined name 'convert2np'
1
```

**Comment by shubhtuls** [comment]
Thanks for pointing this out! Updated the file to import it.
