### ISSUE TITLE
404 error while downloading cachedir.tar.gz

### ISSUE THREAD

**Issue by XiangMochu** [akanazawa/cmr#21]
When I tried to download CUB annotation file by running:
`wget https://people.eecs.berkeley.edu/~shubhtuls/cachedir/cmr/cachedir.tar.gz`
I got 404 error. 
Is this file currently available for downloading?

**Comment by Weipeilang** [comment]
I  met the same problem,does any one solve it?

**Comment by shubhtuls** [comment]
Sorry about the missing link. Please see #7

**Comment by Weipeilang** [comment]
I had download the file,thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shubham Tulsiani"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 晚上11:58
收件人:&nbsp;"akanazawa/cmr"<cmr@noreply.github.com&gt;;
抄送:&nbsp;"If you,if I"<2546954766@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [akanazawa/cmr] 404 error while downloading cachedir.tar.gz (#21)




Sorry about the missing link. Please see #7

**Comment by lulianLiu** [comment]
> load the file,thank you
> […](#)
Can you provide datasets for me ?
