### ISSUE TITLE
Update to PyTorch1.x and Python3, remove chainer/cupy dependancy.

### ISSUE THREAD

**Issue by chenyuntc** [akanazawa/cmr#24]
Nice work! I've been working on a similar task, your code is clean and intuitive, a good start for the project.

But I struggle to set up the env. So I make some updates:

- upgrade support to Python3
Python 2 support ends today.

- upgrade to PyTorch 1.3
PyTorch 0.3 was like two years ago.

- Remove chainer/cupy dependancy.
Setting up cupy is too complicated and now there is [pytorch version neural renderer](https://github.com/daniilidis-group/neural_renderer)

The repo is in [chenyuntc/cmr](https://github.com/chenyuntc/cmr).
I can make a pull request if you would like.

**Comment by shubhtuls** [comment]
Hi @chenyuntc ,
Thanks for making the code python3 and pytorch 1.x compatible! I think given Angjoo and I are no longer actively maintaining this codebase, will will just link to your implementation from our README to direct interested people.

Although would it be possible for you to share some sample results that the updated code gives so we're sure that the updates to the neural renderer etc. didn't break anything? Thanks!

**Comment by chenyuntc** [comment]
Hi @shubhtuls 

Following is the comparison of evaluation results and visualization:

## Results from the pretrain model (500 epoch)

```
results.mat mean iou 0.706, pck.1 0.815, pck.15 0.931
results_sfm_camera.mat mean iou 0.741, pck.1 0.923, pck.15 0.983
results_sfm_meanshape_sfm_camera.mat mean iou 0.589, pck.1 0.913, pck.15 0.975
```

## Results of the model trained from scratch (200 epoch)
```
results.mat mean iou 0.693, pck.1 0.798, pck.15 0.923
results_sfm_camera.mat mean iou 0.737, pck.1 0.928, pck.15 0.98
results_sfm_meanshape.mat mean iou 0.565, pck.1 0.783, pck.15 0.914
```

![image1](https://user-images.githubusercontent.com/9301117/72230199-e955f780-3581-11ea-8935-208582087493.jpg)

![image2](https://user-images.githubusercontent.com/9301117/72230200-e955f780-3581-11ea-9ee5-27314bdc7a7f.png)

I will update the results after it finishes training.

**Comment by shubhtuls** [comment]
Thanks a lot @chenyuntc for the efforts in updating the code and sharing sample results!

**Comment by chenyuntc** [comment]
Hi @shubhtuls, after training the model from scratch with my code for 500 epochs,  the results are the following.
1. IoU curve is very close to the figure in the paper.
 
![image](https://user-images.githubusercontent.com/9301117/72488670-a85b1e80-37df-11ea-9d56-10f9ac0a8ad2.png)


2. Interactive mesh visualization
please check [ my mesh visualization in plotly](https://yun.sfo2.digitaloceanspaces.com/t/mesh.html). Plotly only supports face color, no UV map :cry: 


I think the issue is almost done. Feel free to close it.
