### ISSUE TITLE
Data Incomplete 

### ISSUE THREAD

**Issue by thusiyuan** [akanazawa/cmr#3]
Hi, 
It seems the 'testval_cub_cleaned.mat' and 'train_cub_cleaned.mat' downloaded from https://people.eecs.berkeley.edu/~kanazawa/cachedir/cmr/cachedir.tar.gz are incomplete since they are 45 bytes only.

Thanks.

**Comment by shubhtuls** [comment]
Hi,
Thanks for pointing this out. Please use [https://people.eecs.berkeley.edu/~shubhtuls/cachedir/cmr/cachedir.tar.gz](https://people.eecs.berkeley.edu/~shubhtuls/cachedir/cmr/cachedir.tar.gz) instead.

**Comment by touranisatyajit** [comment]
Hi,
It seems like the link given above https://people.eecs.berkeley.edu/~shubhtuls/cachedir/cmr/cachedir.tar.gz  does not work. Could you please provide the necessary updated link or files? 
Thanks in advance :)

**Comment by shubhtuls** [comment]
Hi,
Yes, unfortunately my Berkeley page is no longer active. A (temporary) copy of the data is [here](https://www.dropbox.com/sh/ea3yprgrcjuzse5/AAB476Nn0Lwbrt3iuedB9yzIa?dl=0) (until I find a better data hosting solution!).
