### ISSUE TITLE
Experiment on PASCAL3D+ dataset

### ISSUE THREAD

**Issue by yd-yin** [akanazawa/cmr#5]
Hi, I'm a beginner in 3d reconstruction. It's a really impressive work!
I'm now trying to implement it on PASCAL3D+ dataset, facing some problems on camera pose.
I find PASCAL3D+ dataset offer cam_pose in azi/ele system for each picture and the perspective projection codes. I just wonder how did you process the dataset to match cmr?
1. Simply run SfM again, ignoring the ground-truth cam_pose provided by PASCAL3D+?
2. Calculate the scale/trans/rotation for PASCAL correspond to CUB dataset? But I don't know if it's ok because PASCAL is under perspective projection and CUB is under weak-perspective projection. 
3. Rewrite python codes to project PASCAL using perspective camera?
If I want to do this, I guess the main problem would be how to adjust neural renderer to match the projection.

I'd really appreciate it if you could offer any ideas/materials/codes in this. Thanks a lot!

**Comment by shubhtuls** [comment]
Hi,
Thanks for the interest in the code. We created a different branch [p3d](https://github.com/akanazawa/cmr/tree/p3d) with some [initial instructions](https://github.com/akanazawa/cmr/blob/p3d/preprocess/pascal/pascal.md) on preprocessing/training using PASCAL 3D.

I think this part of the release may not be as stable as the remaining code base that uses the CUB dataset, but should be a good starting point for the things you might be interested in. Please let us know if you have any followups.

**Comment by nikhilaravi** [comment]
@shubhtuls is there a trained model available for the the car and aeroplane classes?

**Comment by hideonInternet** [comment]
@akanazawa @shubhtuls Hi, how do you evaluate the IOU metric on PASCAL 3D+.  IOU = intersection / union  or IOU = intersection / (union - intersection)

**Comment by Weipeilang** [comment]
Hi,when I ran the "python instance_segment.py...." as follows,I met the problem that 
"loading annotations into memory...
Done (t=0.65s)
creating index...
index created!
Traceback (most recent call last):
  File "instance_segment.py", line 31, in <module>
    from core.config import assert_and_infer_cfg
ImportError: No module named core.config"
Is it the lack of file?or how can I solve this problem?
Thank you

**Comment by akanazawa** [comment]
Hi, 

This sounds like some issue with python import, see "ImportError: No module named core.config"
does that core.config exist in your path? If it does possibly you're running the code from a wrong directory. 

Best

**Comment by Weipeilang** [comment]
Thanks for your reply！
I solved that problem by putting the above path is set to "/ path/to/Detectron/detectron".But now I have a new problem, as shown in the picture.Configuring the environment is very difficult for me, so  I was wondering if you could give me a more detailed description of how to implement running "python instance_segment.py".
Thank you once again.
![2019-12-21 18-48-48屏幕截图](https://user-images.githubusercontent.com/40757437/71308224-b7df8580-2434-11ea-9cd1-3cc2f88aef46.png)

**Comment by Weipeilang** [comment]
I successfully prepared the data set according to your [method](https://github.com/akanazawa/cmr/blob/p3d/preprocess/pascal/pascal.md), which is similar to the format of the bird.I had a problem training, I only trained 50 or 100 iterations, the car model looked like this, 
![W)POC6Z4X824NP6BT$7I69S](https://user-images.githubusercontent.com/40757437/77385813-3812df80-6dc4-11ea-94f2-7825348c0648.png)
![image](https://user-images.githubusercontent.com/40757437/77386051-dd2db800-6dc4-11ea-96e0-03fea43ea3e9.png)
500 or 700 times, the model looked like this.
![CM(Y)JA_BY V`@TWENP)_ I](https://user-images.githubusercontent.com/40757437/77386086-f9315980-6dc4-11ea-9ffd-7f206b0d1e4c.png)
![O{FN}9JQ65SXTCR41S8`}EU](https://user-images.githubusercontent.com/40757437/77386089-fdf60d80-6dc4-11ea-9251-48f9d71a07f0.png)
I want to ask if there are any details that I didn't notice, and how to achieve the good results in your paper
![image](https://user-images.githubusercontent.com/40757437/77386184-31d13300-6dc5-11ea-8ee9-0d0793ec4761.png)

**Comment by Weipeilang** [comment]
@akanazawa

**Comment by akanazawa** [comment]
Hi Weipeilang,

Yeah this looks like there's something wrong, but others have successfully trained on pascal car and we did not change any hyperparameters for it, so as long as you can train on the bird dataset you should be able to train on the cars as well. 
I suggest you visualize the dataset to make sure that the images + annotations look correct, if the mean shape looks correct, and make sure you can train on the bird dataset. 

Best,

Angjoo

**Comment by anandbhattad** [comment]
Matlab preprocessing with SFM failing at multiple locations. It would be really helpful if you could provide a cache dataset and pre-trained models that were used for PASCAL3D+ experiments.  Thanks a lot!
