### ISSUE TITLE
Simple question about your implementation

### ISSUE THREAD

**Issue by gsygsy96** [akanazawa/cmr#9]
I have a simple question. In mesh_net.py Line289,290, you set img_H and img_W as :

- img_H = int(2**np.floor(np.log2(np.sqrt(num_faces) * opts.tex_size)))
- img_W = 2 * img_H

Could you explain the reason?

**Comment by shubhtuls** [comment]
This was just a heuristic to ensure that the number of pixels in the UV texture image are of a similar order as number of texture samples across all faces. The code represents each face with 'opts.tex_size * opts.tex_size' samples, so an image with height/width of 'np.sqrt(num_faces) * opts.tex_size' would have similar number of pixels. The additional code enforces that the sizes are a power of 2, so it is easily predictable via an up-convolutional CNN.
